version: "3"
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile_python
    container_name: flask_container
    command: bash -c 'cd ./backend; python3 app.py'
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
  vue:
    build:
      context: .
      dockerfile: Dockerfile_node
    container_name: vue_container
    tty: true
    command: sh -c 'cd ./frontend; pwd;yarn install --ignore-optional; yarn run build; yarn dev'
    volumes:
      - ./:/usr/src/app
    ports:
      - "8080:8080"
